# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 15 
  - name: " "
    identifier: home_item 
    weight: 10 
  - name: News
    url: 'news/'
    weight: 20  
  - name: Blog
    url: 'blog/'
    weight: 30
  - name: MLOPT
    url: 'mlopt/'
    weight: 40
  - name: Publications
    url: 'publication/'
    weight: 50

# sub-menu:
  
  - name: Skills & Interests
    parent: home_item
    url: '#skill'
    weight: 11
  - name: Work Experience
    parent: home_item
    url: '#work'
    weight: 12
  - name: Education
    parent: home_item
    url: '#edu'
    weight: 13
  - name: Latest News
    parent: home_item
    url: '#Latest_news'
    weight: 14
  - name: Contact
    parent: home_item
    url: '#contact'
    weight: 15

  # - name: Team
  #   parent: ds_project
  #   url: 'ds_team/'
  #   weight: 41
  # - name: Project
  #   parent: mlor
  #   url: 'ds_project/'
  #   weight: 42

  # - name: ML+OPT
  #   parent: research
  #   url: 'mlopt/'
  #   weight: 51
  # - name: Publications
  #   parent: research
  #   url: 'publication/'
  #   weight: 52

  

  # - name: About
  #   url: '#about'
  #   weight: 10
  # - name: News
  #   url: 'news/'
  #   weight: 20
  # - name: Blog
  #   url: 'blog/'
  #   weight: 30
  # # - name: Talks
  # #   url: 'event/'
  # #   weight: 40
  # - name: Publications
  #   url: 'publication/'
  #   weight: 50
  # - name: Contact
  #   url: '#contact'
  #   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
